// <auto-generated />
using System;
using IdentityService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260827095937_AddAdministrationAuditEntries")]
    partial class AddAdministrationAuditEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityService.Domain.Entities.AdministrationAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AdministrationAuditEntries", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d001"),
                            Description = "Read own profile.",
                            Name = "identity.profile.read"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d002"),
                            Description = "Refresh authentication token.",
                            Name = "identity.token.refresh"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d003"),
                            Description = "Submit identity documents for KYC verification.",
                            Name = "Kyc.Submit"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d004"),
                            Description = "Review and decide KYC verification cases.",
                            Name = "Kyc.Verify"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d005"),
                            Description = "Read policy records.",
                            Name = "Policy.Read"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d006"),
                            Description = "Create or update own policy records.",
                            Name = "Policy.Write"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d007"),
                            Description = "Create or update policy records for any customer.",
                            Name = "Policy.Write.Any"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d008"),
                            Description = "Approve or decline policy applications.",
                            Name = "Policy.Approve"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d009"),
                            Description = "Read claim records.",
                            Name = "Claim.Read"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d010"),
                            Description = "Approve or decline claim cases.",
                            Name = "Claim.Decide"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d011"),
                            Description = "Read payment records.",
                            Name = "Payment.Read"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d012"),
                            Description = "Process approved payment refunds.",
                            Name = "Payment.Refund"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d013"),
                            Description = "Read customer records.",
                            Name = "Customer.Read"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d014"),
                            Description = "Create or update customer records.",
                            Name = "Customer.Write"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d015"),
                            Description = "Read KYC audit activity.",
                            Name = "Kyc.Audit.Read"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d016"),
                            Description = "View operational and compliance reports.",
                            Name = "Reporting.View"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d017"),
                            Description = "Manage platform user access.",
                            Name = "Identity.Users.Manage"
                        },
                        new
                        {
                            Id = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d018"),
                            Description = "Manage platform roles and permissions.",
                            Name = "Identity.Roles.Manage"
                        });
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa001"),
                            Description = "Default customer role for platform users.",
                            Name = "Customer"
                        },
                        new
                        {
                            Id = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa002"),
                            Description = "Reviews and decides KYC verification cases.",
                            Name = "KycReviewer"
                        },
                        new
                        {
                            Id = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa003"),
                            Description = "Reviews and approves insurance policy applications.",
                            Name = "PolicyUnderwriter"
                        },
                        new
                        {
                            Id = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa004"),
                            Description = "Reviews and decides insurance claim cases.",
                            Name = "ClaimsAdjuster"
                        },
                        new
                        {
                            Id = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa005"),
                            Description = "Handles payment operations and refunds.",
                            Name = "PaymentOperations"
                        },
                        new
                        {
                            Id = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa006"),
                            Description = "Assists customers with account and policy enquiries.",
                            Name = "SupportAgent"
                        },
                        new
                        {
                            Id = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa007"),
                            Description = "Audits KYC activity and reviews compliance reporting.",
                            Name = "ComplianceOfficer"
                        },
                        new
                        {
                            Id = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa008"),
                            Description = "Manages platform users, roles, and operational access.",
                            Name = "PlatformAdmin"
                        });
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa001"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d001")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa001"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d002")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa001"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d003")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa001"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d013")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa001"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d014")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa001"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d005")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa001"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d006")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa002"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d004")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa003"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d005")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa003"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d007")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa003"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d008")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa004"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d009")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa004"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d010")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa005"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d011")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa005"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d012")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa006"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d013")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa006"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d014")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa006"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d005")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa006"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d009")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa007"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d015")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa007"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d016")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa008"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d017")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa008"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d018")
                        },
                        new
                        {
                            RoleId = new Guid("6a34f111-5c2b-4a86-95a9-6d622c2fa008"),
                            PermissionId = new Guid("d43137c8-2faf-4b99-b36a-b71d39a9d007")
                        });
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("IdentityService.Domain.Entities.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("IdentityService.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityService.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("IdentityService.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityService.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IdentityService.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
